apiVersion: v1
kind: Service
metadata:
  labels:
    service: connection-api
  name: connection-api
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30003
  selector:
    service: connection-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: connection-api
  name: connection-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: connection-api
  template:
    metadata:
      labels:
        service: connection-api
    spec:
      containers:
      - image: vaibhavg12/connection-api:latest
        name: connection-api
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "128m"
        livenessProbe:
          tcpSocket:
            port: 5005
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 5005
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
