# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import app.udaconnect.proto.connect_pb2 as connect__pb2


class ConnectMessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindConnections = channel.unary_unary(
                '/ConnectMessageService/FindConnections',
                request_serializer=connect__pb2.SearchMessage.SerializeToString,
                response_deserializer=connect__pb2.ConnectMessages.FromString,
                )


class ConnectMessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindConnections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectMessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindConnections': grpc.unary_unary_rpc_method_handler(
                    servicer.FindConnections,
                    request_deserializer=connect__pb2.SearchMessage.FromString,
                    response_serializer=connect__pb2.ConnectMessages.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ConnectMessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConnectMessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindConnections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ConnectMessageService/FindConnections',
            connect__pb2.SearchMessage.SerializeToString,
            connect__pb2.ConnectMessages.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
