# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connect.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rconnect.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x01\n\rSearchMessage\x12\x11\n\tperson_id\x18\x01 \x01(\x03\x12.\n\nstart_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06meters\x18\x04 \x01(\x02\"X\n\rPersonMessage\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t\"\x9b\x01\n\x0fLocationMessage\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tperson_id\x18\x02 \x01(\x03\x12\x11\n\tlongitude\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\t\x12\x31\n\rcreation_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\twkt_shape\x18\x06 \x01(\t\"T\n\x0e\x43onnectMessage\x12\"\n\x08location\x18\x01 \x01(\x0b\x32\x10.LocationMessage\x12\x1e\n\x06person\x18\x02 \x01(\x0b\x32\x0e.PersonMessage\"7\n\x0f\x43onnectMessages\x12$\n\x0b\x63onnections\x18\x01 \x03(\x0b\x32\x0f.ConnectMessage2L\n\x15\x43onnectMessageService\x12\x33\n\x0f\x46indConnections\x12\x0e.SearchMessage\x1a\x10.ConnectMessagesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connect_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEARCHMESSAGE._serialized_start=51
  _SEARCHMESSAGE._serialized_end=195
  _PERSONMESSAGE._serialized_start=197
  _PERSONMESSAGE._serialized_end=285
  _LOCATIONMESSAGE._serialized_start=288
  _LOCATIONMESSAGE._serialized_end=443
  _CONNECTMESSAGE._serialized_start=445
  _CONNECTMESSAGE._serialized_end=529
  _CONNECTMESSAGES._serialized_start=531
  _CONNECTMESSAGES._serialized_end=586
  _CONNECTMESSAGESERVICE._serialized_start=588
  _CONNECTMESSAGESERVICE._serialized_end=664
# @@protoc_insertion_point(module_scope)
